version: '3.1'
services:
    php-apache:
        build:
            context: .
            dockerfile: ./docker/php-apache/Dockerfile
#        container_name: php-apache
        ports:
            - "8080:80"
            - "4430:443"
        links:
          - mysql
        volumes:
            - ./:/var/www/html
        environment:
          WEB_DOCUMENT_ROOT: /var/www/html
        working_dir: /var/www/html 

    mysql:
        image: mysql:5.7
        container_name: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0 --sql-mode=''
        volumes:
#            - ./../database/create.sql:/docker-entrypoint-initdb.d/schema.sql
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - "8306:3306"
        env_file: ./docker/mysql/mysql.env

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8081:8080
        environment:
          ADMINER_DEFAULT_SERVER: mysql
          ADMINER_PLUGINS: "edit-foreign"
